import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/loader.css";
import "@/styles/admin.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body
        className="antialiased text-slate-800 mx-auto"
        style={{
          background: `radial-gradient(1200px 600px at 10% 10%, #fff6ea 0%, transparent 60%),
                       radial-gradient(900px 500px at 90% 20%, #e9fff8 0%, transparent 60%),
                       linear-gradient(135deg, #fbf8f3, #f6fbf9)`,
        }}
      >
          {children}
      </body>
    </html>
  );
}

